/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/cesiumPage': RouteRecordInfo<
      '/cesiumPage',
      '/cesiumPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/MapboxGLMap': RouteRecordInfo<
      '/MapboxGLMap',
      '/MapboxGLMap',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/mapPage': RouteRecordInfo<
      '/mapPage',
      '/mapPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/threePage': RouteRecordInfo<
      '/threePage',
      '/threePage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/[id]': RouteRecordInfo<
      '/user/[id]',
      '/user/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/cesiumPage.vue': {
      routes:
        | '/cesiumPage'
      views:
        | never
    }
    'src/pages/MapboxGLMap.vue': {
      routes:
        | '/MapboxGLMap'
      views:
        | never
    }
    'src/pages/mapPage.vue': {
      routes:
        | '/mapPage'
      views:
        | never
    }
    'src/pages/threePage.vue': {
      routes:
        | '/threePage'
      views:
        | never
    }
    'src/pages/user/[id].vue': {
      routes:
        | '/user/[id]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
